//ELEMENTS OBJECT TO RETAIN ALL QUERY SELECTORS FOR REUSABILITY
export const el = {
  dataSettingsTheme: document.querySelector("[data-settings-theme]"),
  dataListBtn: document.querySelector("[data-list-button]"),
  dataSettingsForm: document.querySelector("[data-settings-form]"),
  dataSearchCancel: document.querySelector("[data-search-cancel]"),
  dataSearchOverlay: document.querySelector("[data-search-overlay]"),
  dataSettingsOverlay: document.querySelector("[data-settings-overlay]"),
  dataSettingsCancel: document.querySelector("[data-settings-cancel]"),
  dataHeaderSearch: document.querySelector("[data-header-search]"),
  dataHeaderSettings: document.querySelector("[data-header-settings]"),
  dataListClose: document.querySelector("[data-list-close]"),
  dataListItems: document.querySelector("[data-list-items]"),
  dataSearchGenres: document.querySelector("[data-search-genres]"),
  dataSearchAuthors: document.querySelector("[data-search-authors]"),
  dataSearchForm: document.querySelector("[data-search-form]"),
  dataSearchTitle: document.querySelector("[data-search-title]"),
  dataListActive: document.querySelector("[data-list-active]"),
  dataListBlur: document.querySelector("[data-list-blur]"),
  dataListImg: document.querySelector("[data-list-image]"),
  dataListTitle: document.querySelector("[data-list-title]"),
  dataListSubtitle: document.querySelector("[data-list-subtitle]"),
  dataListDesc: document.querySelector("[data-list-description]"),
  dataListMessage: document.querySelector("[data-list-message]"),
};
